=== maki007/RelationalQueryEvaluator/RelationalQueryEvaluator/data/algebra.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="non_empty_string">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"></xs:minLength>
    </xs:restriction>
  </xs:simpleType>
  
  <!-- agregation -->
  <xs:complexType name="unary_agregate_type">
    <xs:attribute name="argument" type="non_empty_string" use="required"></xs:attribute>
    <xs:attribute name="output" type="non_empty_string" use="required"></xs:attribute>
  </xs:complexType>
  <xs:complexType name="nulary_agregate_type">
    <xs:attribute name="output" type="non_empty_string" use="required"></xs:attribute>
  </xs:complexType>

  <!-- boolean condition -->
  <xs:complexType name="bool_condition">
    <xs:choice>
      <xs:element name="not" type="bool_condition"></xs:element>
      <xs:element name="or" type="binary_bool_condition"></xs:element>
      <xs:element name="and" type="binary_bool_condition"></xs:element>
      <xs:element name="equals" type="bool_operator"></xs:element>
      <xs:element name="not_equals" type="bool_operator"></xs:element>
      <xs:element name="lower" type="bool_operator"></xs:element>
      <xs:element name="lower_or_equals" type="bool_operator"></xs:element>
      <xs:element name="boolean_predicate" type="boolean_predicate"></xs:element>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="binary_bool_condition">
    <xs:choice minOccurs="2" maxOccurs="2">
      <xs:element name="not" type="bool_condition"></xs:element>
      <xs:element name="or" type="binary_bool_condition"></xs:element>
      <xs:element name="and" type="binary_bool_condition"></xs:element>
      <xs:element name="equals" type="bool_operator"></xs:element>
      <xs:element name="not_equals" type="bool_operator"></xs:element>
      <xs:element name="lower" type="bool_operator"></xs:element>
      <xs:element name="lower_or_equals" type="bool_operator"></xs:element>
      <xs:element name="boolean_predicate" type="boolean_predicate"></xs:element>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="bool_operator">
    <xs:choice minOccurs="2" maxOccurs="2">
      <xs:element name="column" type="column"></xs:element>
      <xs:element name="costant" type="constant"></xs:element>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="column">
    <xs:attribute name="name" type="non_empty_string" use="required"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="index">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="column" type="column"></xs:element>
    </xs:sequence>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="clustered"/>
          <xs:enumeration value="unclustered"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="constant">
    <xs:attribute name="type" use="required"></xs:attribute>
    <xs:attribute name="value" use="required"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="boolean_predicate">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="column" type="column"></xs:element>
      <xs:element name="costant" type="constant"></xs:element>
    </xs:choice>
    <xs:attribute name="name" use="required"></xs:attribute>
  </xs:complexType>

  <!-- aritmetic expression -->
  <xs:complexType name="unary_aritmetic_expression">
    <xs:choice minOccurs="1" maxOccurs="1">
      <xs:element name="plus" type="binary_aritmetic_expression"></xs:element>
      <xs:element name="minus" type="binary_aritmetic_expression"></xs:element>
      <xs:element name="times" type="binary_aritmetic_expression"></xs:element>
      <xs:element name="divide" type="binary_aritmetic_expression"></xs:element>
      <xs:element name="aritmetic_function" type="aritmetic_function"></xs:element>
      <xs:element name="column" type="column"></xs:element>
      <xs:element name="costant" type="constant"></xs:element>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="binary_aritmetic_expression">
    <xs:choice minOccurs="2" maxOccurs="2">
      <xs:element name="plus" type="binary_aritmetic_expression"></xs:element>
      <xs:element name="minus" type="binary_aritmetic_expression"></xs:element>
      <xs:element name="times" type="binary_aritmetic_expression"></xs:element>
      <xs:element name="divide" type="binary_aritmetic_expression"></xs:element>
      <xs:element name="aritmetic_function" type="aritmetic_function"></xs:element>
      <xs:element name="column" type="column"></xs:element>
      <xs:element name="costant" type="constant"></xs:element>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="aritmetic_function">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="argument" type="unary_aritmetic_expression"></xs:element>
    </xs:sequence>
    <xs:attribute name="name" use="required"></xs:attribute>
  </xs:complexType>

  <!-- group -->
  <xs:complexType name="group">
    <xs:sequence>
      <xs:element name="parameters">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="group_by" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="column" use="required"></xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="sum" type="unary_agregate_type"></xs:element>
              <xs:element name="min" type="unary_agregate_type"></xs:element>
              <xs:element name="max" type="unary_agregate_type"></xs:element>
              <xs:element name="count"  type="nulary_agregate_type"></xs:element>
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="input" type="unaryoperator"></xs:element>
    </xs:sequence>
  </xs:complexType>
  <!-- unary operator -->
  <xs:complexType name="unaryoperator">
    <xs:choice minOccurs="1" maxOccurs="1">
      <xs:element name="join" type="join"></xs:element>
      <xs:element name="group" type="group"></xs:element>
      <xs:element name="selection" type="selection"></xs:element>
      <xs:element name="table" type="table"></xs:element>
      <xs:element name="union" type="union"></xs:element>
      <xs:element name="antijoin" type="antijoin"></xs:element>
      <xs:element name="column_operations" type="column_operations"></xs:element>
    </xs:choice>
  </xs:complexType>
  <!-- binary operator -->
  <xs:complexType name="binaryoperator">
    <xs:choice minOccurs="2" maxOccurs="2">
      <xs:element name="join" type="join"></xs:element>
      <xs:element name="group" type="group"></xs:element>
      <xs:element name="selection" type="selection"></xs:element>
      <xs:element name="table" type="table"></xs:element>
      <xs:element name="union" type="union"></xs:element>
      <xs:element name="antijoin" type="antijoin"></xs:element>
      <xs:element name="column_operations" type="column_operations"></xs:element>
    </xs:choice>
  </xs:complexType>
  <!-- union -->
  <xs:complexType name="union">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="input" type="binaryoperator" />
    </xs:sequence>
  </xs:complexType>
  <!-- table -->
  <xs:complexType name="table">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="column">
        <xs:complexType>
          <xs:attribute name="name" use="required"></xs:attribute>
          <xs:attribute name="number_of_unique_values" use="optional" type="xs:unsignedLong"></xs:attribute>
          <xs:attribute name="type" use="required" type="non_empty_string"></xs:attribute>
        </xs:complexType>
      </xs:element>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="index" type="index" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute use="optional" name="numberOfRows" type="xs:unsignedLong"></xs:attribute>
    <xs:attribute use="required" name="name"></xs:attribute>
  </xs:complexType>
  
  
  <!-- join -->
  <xs:complexType name="join">
    <xs:sequence>
      <xs:element name="parameters">
        <xs:complexType>
          <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="1">
              <xs:element name="equal_condition" type="equal_condition"></xs:element>
              <xs:element name="less_condition" type="less_condition"></xs:element>
            </xs:choice>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
              <!-- name of output columns with optional rename-->
              <xs:element name="column">
                <xs:complexType>
                  <xs:attribute name="name" use="required"></xs:attribute>
                  <xs:attribute name="newName" use="optional"></xs:attribute>
                  <!-- from which input is this column -->
                  <xs:attribute name="input" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="first"></xs:enumeration>
                        <xs:enumeration value="second"></xs:enumeration>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="input" type="binaryoperator"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- anti join -->
  <xs:complexType name="antijoin">
    <xs:sequence>
      <xs:element name="parameters">
        <xs:complexType>
          <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="1">
              <xs:element name="equal_condition" type="equal_condition"></xs:element>
            </xs:choice>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
              <!-- name of output columns with optional rename-->
              <xs:element name="column">
                <xs:complexType>
                  <xs:attribute name="name" use="required"></xs:attribute>
                  <xs:attribute name="newName" use="optional"></xs:attribute>
                  <!-- from which input is this column -->
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="input" type="binaryoperator"></xs:element>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="equal_condition">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="equals">
        <xs:complexType>
          <xs:sequence minOccurs="2" maxOccurs="2">
            <xs:element name="column" type="column"></xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="less_or_equals_in_join">
    <xs:sequence minOccurs="2" maxOccurs="2">
      <xs:element name="column" type="column"></xs:element>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="less_condition">
    <xs:choice minOccurs="1" maxOccurs="1">
      <xs:element name="and">
        <xs:complexType>
          <xs:choice minOccurs="2" maxOccurs="2">
            <xs:element name="less" type="less_or_equals_in_join"></xs:element>
            <xs:element name="less_or_equals" type="less_or_equals_in_join"></xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
      <xs:element name="less" type="less_or_equals_in_join"></xs:element>
      <xs:element name="less_or_equals" type="less_or_equals_in_join"></xs:element>
    </xs:choice>
  </xs:complexType>

  <!-- selection -->
  <xs:complexType name="selection">
    <xs:sequence>
      <xs:element name="parameters">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="condition" type="bool_condition"></xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="input" type="unaryoperator"></xs:element>
    </xs:sequence>
  </xs:complexType>
  <!-- column operation-->
  <xs:complexType name="column_operations">
    <xs:sequence>
      <xs:element name="parameters">
        <xs:complexType>
          <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="column">
              <xs:complexType>
                <xs:sequence minOccurs="0" maxOccurs="1">
                  <xs:element name="equals" type="unary_aritmetic_expression"></xs:element>
                </xs:sequence>
                <xs:attribute name="name"></xs:attribute>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="input" type="unaryoperator"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- sort - root element-->
  <xs:element name="sort">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="parameters">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="direction" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="asc"></xs:enumeration>
                        <xs:enumeration value="desc"></xs:enumeration>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="column" type="non_empty_string" use="required"></xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="input" type="unaryoperator"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== maki007/RelationalQueryEvaluator/RelationalQueryEvaluator/data/2-4-3noopt.xml
<?xml version="1.0" encoding="utf-8" ?>
<sort xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="algebra.xsd">
  <parameters>
    <parameter column="revenue" direction="desc" />
    <parameter column="o_orderdate" direction="asc" />
  </parameters>
  <input>
    <group>
      <parameters>
        <group_by column="l_orderkey"/>
        <group_by column="o_orderdate" />
        <group_by column="o_shippriority"/>
        <sum argument="x" output="revenue"/>
      </parameters>
      <input>
        <column_operations>
          <parameters>
            <column name="l_orderkey"></column>
            <column name="o_orderdate"></column>
            <column name="o_shippriority"></column>
            <column name="x">
              <equals>
                <times>
                  <column name="l_extendedprice"/>
                  <minus>
                    <constant type="double" value="1"/>
                    <column name="l_discount"/>
                  </minus>
                </times>
              </equals>
            </column>
          </parameters>
          <input>
            <selection>
              <parameters>
                <condition>
                  <and>
                    <and>
                      <equals>
                        <column name="c_mktsegment"/>
                        <constant type="string" value="SEGMENT"/>
                      </equals>
                      <equals>
                        <column name="c_custkey"/>
                        <column name="o_custkey"/>
                      </equals>
                    </and>
                    <and>
                      <and>
                        <lower>
                          <column name="o_orderdate"/>
                          <constant type="date" value="today"/>
                        </lower>
                        <lower>
                          <constant type="date" value="today"/>
                          <column name="l_shipdate"/>
                        </lower>
                      </and>
                      <equals>
                        <column name="l_orderkey"/>
                        <column name="o_orderkey"/>
                      </equals>
                    </and>
                  </and>
                </condition>
              </parameters>
              <input>
                <join>
                  <parameters>
                    <column name="l_orderkey" input="second"/>
                        <column name="o_orderdate" input="second"/>
                        <column name="o_shippriority" input="second"/>
                        <column name="l_extendedprice" input="second"/>
                        <column name="l_shipdate" input="second"/>
                        <column name="l_discount" input="second"/>
                        <column name="o_custkey" input="second"/>
                        <column name="o_orderkey" input="second"/>
                       <column name="c_custkey" input="first"/>
                        <column name="c_mktsegment" input="first"/>
                  </parameters>
                  <input>
                    <table name="customer" numberOfRows="150000">
                      <column name="c_custkey" type="int" />
                      <column name="c_mktsegment" type="int"/>
                    </table>
                    <join>
                      <parameters>
                        <column name="l_orderkey" input="first"/>
                        <column name="o_orderdate" input="second"/>
                        <column name="o_shippriority" input="second"/>
                        <column name="l_extendedprice" input="first"/>
                        <column name="l_shipdate" input="first"/>
                        <column name="l_discount" input="first"/>
                        <column name="o_custkey" input="second"/>
                        <column name="o_orderkey" input="second"/>
                      </parameters>
                      <input>
                        <table name="lineitem" numberOfRows="6000000">
                          <column name="l_orderkey" type="int"></column>
                          <column name="l_shipdate" type="int"/>
                          <column name="l_extendedprice" type="int"/>
                          <column name="l_discount" type="int"/>
                        </table>
                        <table name="orders" numberOfRows="1500000">
                          <column name="o_orderdate" type="int"/>
                          <column name="o_shippriority" type="int"/>
                          <column name="o_orderkey" type="int"/>
                          <column name="o_custkey" type="int" />
                        </table>
                      </input>
                    </join>
                  </input>
                </join>
              </input>
            </selection>
          </input>
        </column_operations>
      </input>
    </group>
  </input>
</sort>

=== maki007/RelationalQueryEvaluator/RelationalQueryEvaluator/data/Antijoin.xml
<?xml version="1.0" encoding="utf-8" ?>
<sort xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="algebra.xsd">
  <parameters>
  </parameters>
  <input>
    <antijoin>
      <parameters>
        <equal_condition>
          <equals>
            <column name="d"/>
            <column name="b"/>
          </equals>
        </equal_condition>
        <column name="d"/>
      </parameters>
      <input>
        <antijoin>
          <parameters>
            <equal_condition>
              <equals>
                <column name="c"/>
                <column name="a"/>
              </equals>
            </equal_condition>
            <column name="c" newName="d"/>
          </parameters>
          <input>
            <table name="z">
              <column name="c" type="int"/>
            </table>
            <table name="x">
              <column name="a" type="int"/>
            </table>
          </input>

        </antijoin>
        <table name="y">
          <column name="b" type="int"/>
        </table>
      </input>
    </antijoin>
  </input>
</sort>

=== maki007/RelationalQueryEvaluator/RelationalQueryEvaluator/data/algebraExampleJoinOnMultipleColumns.xml
<?xml version="1.0" encoding="utf-8" ?>
<sort xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="algebra.xsd">
  <parameters>
  </parameters>
  <input>
    <antijoin>
      <parameters>
        <equal_condition>
          <equals>
            <column name="a1"/>
            <column name="b1"/>
          </equals>
          <equals>
            <column name="a2"/>
            <column name="b2"/>
          </equals>
        </equal_condition>
        <column name="a1" input="first"/>
        <column name="b2" input="second"/>
      </parameters>
      <input>
        <table name="a">
          <column name="a1" type="int"/>
          <column name="a2" type="int"/>
        </table>
        <table name="b">
          <column name="b1" type="int"/>
          <column name="b2" type="int"/>
        </table>
      </input>
    </antijoin>
  </input>
</sort>

=== maki007/RelationalQueryEvaluator/RelationalQueryEvaluator/data/algebraExampleIntersection.xml
<?xml version="1.0" encoding="utf-8" ?>
<sort xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="algebra.xsd">
  <parameters>
  </parameters>
  <input>
    <intersection>
      <input>
        <table name="people_from_city">
          <column name="name"/>
        </table>
        <table name="people_from_city">
          <column name="name" unique="true" />
        </table>
      </input>
    </intersection>
  </input>
</sort>

=== maki007/RelationalQueryEvaluator/RelationalQueryEvaluator/data/algebraExampleCrossJoin.xml
<?xml version="1.0" encoding="utf-8" ?>
<sort xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="algebra.xsd">
  <parameters>
  </parameters>
  <input>
    <join>
      <parameters>
        <column name="name" input="first"/>
        <column name="name" newName="country_name" input="second"/>
      </parameters>
      <input>
        <table name="users">
          <column name="name"/>
          <column name="country_id"/>
        </table>
        <table name="countries"> 
          <column name="id"/>
          <column name="name" />
        </table>
      </input>
    </join>
  </input>
</sort>

=== maki007/RelationalQueryEvaluator/RelationalQueryEvaluator/data/algebraExampleSimpleJoin.xml
<?xml version="1.0" encoding="utf-8" ?>
<sort xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="algebra.xsd">
  <parameters>
  </parameters>
  <input>
    <join>
      <parameters>
        <equal_condition>
          <equals>
            <column name="a"/>
            <column name="b" />
          </equals>
        </equal_condition>
        <column name="a" input="first"/>
        <column name="b" input="second"/>
      </parameters>
      <input>
        <table name="p">
          <column name="a" type="int"/>
          <index name="indexa" type="clustered">
            <column name="a" order="asc"/>
          </index>
        </table>
        <table name="q">
          <column name="b" type="int"/>
          <index name="index" type="unclustered">
            <column name="b" order="asc"/>
          </index>
        </table>
      </input>
    </join>
  </input>
</sort>

=== maki007/RelationalQueryEvaluator/RelationalQueryEvaluator/data/Index.xml
<?xml version="1.0" encoding="utf-8" ?>
<sort xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="algebra.xsd">
  <parameters>
    <parameter column="a" direction="asc"/>
  </parameters>
  <input>
    <selection>
      <parameters>
        <condition>
          <lower>
            <column name="a"/>
            <constant type="int" value="5"/>
          </lower>
        </condition>
      </parameters>
      <input>
        <table name="x" numberOfRows="100000">
          <column name="a" type="int" number_of_unique_values="50000"/>
          <index name="index" type="unclustered">
            <column name="a" order="asc"/>
          </index>
        </table>
      </input>
    </selection>
  </input>
</sort>

=== maki007/RelationalQueryEvaluator/RelationalQueryEvaluator/data/Union.xml
<?xml version="1.0" encoding="utf-8" ?>
<sort xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="algebra.xsd">
  <parameters>
  </parameters>
  <input>
    <union>
      <input>
        <table name="people_from_city">
          <column name="name" type="string" />
        </table>
        <union>
          <input>
            <table name="people_from_city">
              <column name="name" type="string"/>
            </table>
            <table name="people_from_city">
              <column name="name" type="string" />
            </table>
          </input>
        </union>   
      </input>
    </union>
  </input>
</sort>
